============================================================
  Generated by:           Genus(TM) Synthesis Solution 21.14-s082_1
  Generated on:           May 06 2026  01:41:38 pm
  Module:                 counter
  Operating conditions:   slow (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

                              
   Gate    Instances   Area   Library 
--------------------------------------
AND2X1             1    4.541    slow 
CLKINVX1           2    4.541    slow 
DFFRHQX2           1   21.193    slow 
DFFRX2             1   22.707    slow 
MX2X1              1    6.812    slow 
NAND2BX1           1    4.541    slow 
NAND2XL            1    3.028    slow 
OAI211X1           2   10.597    slow 
OR3XL              1    6.055    slow 
SDFFRHQX2          2   51.469    slow 
--------------------------------------
total             13  135.485         


                                        
     Type      Instances   Area  Area % 
----------------------------------------
sequential             4  95.369   70.4 
inverter               2   4.541    3.4 
logic                  7  35.574   26.3 
physical_cells         0   0.000    0.0 
----------------------------------------
total                 13 135.485  100.0
