// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May  6 2026 13:41:37 IST (May  6 2026 08:11:37 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count);
  input clk, m, rst;
  output [3:0] count;
  wire clk, m, rst;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  DFFRHQX2 \count_reg[1] (.RN (rst), .CK (clk), .D (n_9), .Q
       (count[1]));
  OAI211X1 g238__2398(.A0 (m), .A1 (n_2), .B0 (n_3), .C0 (n_7), .Y
       (n_9));
  MX2X1 g239__5107(.A (n_4), .B (n_7), .S0 (n_6), .Y (n_8));
  AND2X1 g240__6260(.A (n_4), .B (n_7), .Y (n_5));
  OAI211X1 g241__4319(.A0 (count[0]), .A1 (count[1]), .B0 (m), .C0
       (n_2), .Y (n_3));
  NAND2BX1 g242__8428(.AN (n_2), .B (m), .Y (n_4));
  OR3XL g243__5526(.A (m), .B (count[0]), .C (count[1]), .Y (n_7));
  NAND2XL g245__6783(.A (count[0]), .B (count[1]), .Y (n_2));
  CLKINVX1 g248(.A (count[2]), .Y (n_6));
  CLKINVX1 g246(.A (count[3]), .Y (n_0));
  DFFRX2 \count_reg[0] (.RN (rst), .CK (clk), .D (n_1), .Q (count[0]),
       .QN (n_1));
  SDFFRHQX2 \count_reg[3] (.RN (rst), .CK (clk), .D (n_0), .SI
       (count[3]), .SE (n_8), .Q (count[3]));
  SDFFRHQX2 \count_reg[2] (.RN (rst), .CK (clk), .D (n_6), .SI
       (count[2]), .SE (n_5), .Q (count[2]));
endmodule
