============================================================
  Generated by:           Genus(TM) Synthesis Solution 21.14-s082_1
  Generated on:           May 08 2026  03:03:26 pm
  Module:                 siso_right_shift
  Operating conditions:   slow (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

                            
  Gate    Instances   Area  Library 
------------------------------------
DFFRHQX1          3  61.309    slow 
DFFRHQX2          1  21.193    slow 
INVXL             1   2.271    slow 
------------------------------------
total             5  84.773         


                                       
     Type      Instances  Area  Area % 
---------------------------------------
sequential             4 82.502   97.3 
inverter               1  2.271    2.7 
physical_cells         0  0.000    0.0 
---------------------------------------
total                  5 84.773  100.0
