// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May  8 2026 15:03:25 IST (May  8 2026 09:33:25 UTC)

// Verification Directory fv/siso_right_shift 

module siso_right_shift(clk, reset, serial_in, serial_out);
  input clk, reset, serial_in;
  output serial_out;
  wire clk, reset, serial_in;
  wire serial_out;
  wire [3:0] shift_reg;
  wire n_0;
  DFFRHQX2 \shift_reg_reg[0] (.RN (n_0), .CK (clk), .D (shift_reg[1]),
       .Q (serial_out));
  DFFRHQX1 \shift_reg_reg[1] (.RN (n_0), .CK (clk), .D (shift_reg[2]),
       .Q (shift_reg[1]));
  DFFRHQX1 \shift_reg_reg[2] (.RN (n_0), .CK (clk), .D (shift_reg[3]),
       .Q (shift_reg[2]));
  DFFRHQX1 \shift_reg_reg[3] (.RN (n_0), .CK (clk), .D (serial_in), .Q
       (shift_reg[3]));
  INVXL g7(.A (reset), .Y (n_0));
endmodule
